# **Scrapping Google Play Review Jenius App**

Pada tahap pengumpulan data, digunakan teknik web scrapping pada platform Google Play Store dengan target aplikasi perbankan digital Jenius. Ekstraksi ulasan pengguna dilakukan menggunakan library **`google-play-scraper`** dengan memanfaatkan fungsi **`reviews_all`** yang memungkinkan pengambilan data secara menyeluruh tanpa batasan jumlah. Konfigurasi scraping diarahkan pada identifikasi paket aplikasi **`com.spotify.music`** dengan parameter bahasa ditetapkan pada Bahasa Indonesia (**`'id'`**) guna memfokuskan perolehan data pada ulasan berbahasa Indonesia. Keseluruhan ulasan yang tersedia diambil menggunakan metode pengurutan berdasarkan ulasan terbaru **`(Sort.NEWEST)`** untuk menjamin relevansi dataset dengan kondisi aktual aplikasi pada saat penelitian dilakukan. Tahapan ini berfungsi sebagai fondasi pembangunan dataset primer yang akan menjadi bahan analisis pada proses selanjutnya.

## Instalasi Library

In [16]:
from google_play_scraper import app, reviews_all, Sort
from datetime import datetime
import pandas as pd
import numpy as np

## Detail Information Jenius App

In [17]:
# 1. Mengambil detail aplikasi menggunakan App ID Spotify
result = app(
    'com.spotify.music',
    lang='id',
    country='id'
)

# 2. Konversi Timestamp ke Format Tanggal Manusia
dt_object = datetime.fromtimestamp(result['updated'])
tanggal = dt_object.strftime('%d %B %Y, %H:%M WIB')

# 3. Menampilkan informasi spesifik terkait update
print(f"Nama Aplikasi     : {result['title']}")
print(f"Versi Terbaru     : {result['version']}")
print(f"Terakhir Diupdate  : {tanggal}")

# 4. Menampilkan dalam bentuk DataFrame
df_detail = pd.DataFrame([result])
df_detail['updated_formatted'] = tanggal
display(df_detail[['title', 'version', 'updated_formatted', 'installs']])

Nama Aplikasi     : Spotify: Music dan Podcast
Versi Terbaru     : Varies with device
Terakhir Diupdate  : 31 March 2026, 22:00 WIB

,title,version,updated_formatted,installs
0,Spotify: Music dan Podcast,Varies with device,"31 March 2026, 22:00 WIB",1.000.000.000+

##Scrapping Jenius App Review

In [20]:
# 1. Proses scrap
spotify_reviews_id = reviews_all(
    'com.spotify.music',
    sleep_milliseconds=0,
    lang='id',
    country='id',
    sort=Sort.NEWEST,
)

print(f'✅ Scraping selesai! Total ulasan terkumpul: {len(spotify_reviews_id):,}')

# 2. Menyimpan ke DataFrame
df_spotify_id = pd.DataFrame(np.array(spotify_reviews_id), columns=['content'])
df_spotify_id = df_spotify_id.join(pd.DataFrame(df_spotify_id.pop('content').tolist()))

print(f'\nJumlah baris  : {df_spotify_id.shape[0]:,}')
print(f'Jumlah kolom  : {df_spotify_id.shape[1]}')

df_spotify_id.head()

✅ Scraping selesai! Total ulasan terkumpul: 482,756

Jumlah baris  : 482,756
Jumlah kolom  : 11

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,95fe611e-c2b2-435c-bba2-bd589c7d8cc6,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,terima kasih Spotify sudah menyediakan lagu_la...,5,0,NaN,2026-04-07 13:41:34,NaN,NaT,NaN
1,2c563637-cfe6-4dcc-9b2e-1e1ab3f3883a,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,👍🏼👍🏼👍🏼,5,0,9.1.32.2083,2026-04-07 13:33:14,NaN,NaT,9.1.32.2083
2,a5b1eaad-3605-4c20-b55a-1cb6bebeb857,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,sebenarnya ini tuh udah bagus banget apknya cu...,4,0,NaN,2026-04-07 13:31:21,NaN,NaT,NaN
3,05c4415f-1a32-4b31-9f75-1c8b725f3e11,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,bagus banget,5,0,NaN,2026-04-07 13:08:57,NaN,NaT,NaN
4,d5236114-519c-4502-a94f-571f5d25a9eb,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Bagus sekali,5,0,9.1.34.2060,2026-04-07 13:00:41,NaN,NaT,9.1.34.2060

In [22]:
# 3. Simpan ke file csv
output_path = "../out/rawdata_spotify_id.csv"
df_spotify_id.to_csv(output_path, index=False, encoding="utf-8")
print(f'\n✅ Data berhasil disimpan ke: {output_path}')

✅ Data berhasil disimpan ke: ../out/rawdata_spotify_id.csv

In [23]:
display(pd.concat([df_spotify_id.head(), df_spotify_id.tail()]))

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,95fe611e-c2b2-435c-bba2-bd589c7d8cc6,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,terima kasih Spotify sudah menyediakan lagu_la...,5,0,NaN,2026-04-07 13:41:34,NaN,NaT,NaN
1,2c563637-cfe6-4dcc-9b2e-1e1ab3f3883a,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,👍🏼👍🏼👍🏼,5,0,9.1.32.2083,2026-04-07 13:33:14,NaN,NaT,9.1.32.2083
2,a5b1eaad-3605-4c20-b55a-1cb6bebeb857,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,sebenarnya ini tuh udah bagus banget apknya cu...,4,0,NaN,2026-04-07 13:31:21,NaN,NaT,NaN
3,05c4415f-1a32-4b31-9f75-1c8b725f3e11,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,bagus banget,5,0,NaN,2026-04-07 13:08:57,NaN,NaT,NaN
4,d5236114-519c-4502-a94f-571f5d25a9eb,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Bagus sekali,5,0,9.1.34.2060,2026-04-07 13:00:41,NaN,NaT,9.1.34.2060
482751,ce6757d6-3ab0-43db-bbef-0fedd8e1c1d2,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Angel lia,4,0,1.1.0.113,2014-06-11 07:54:42,NaN,NaT,1.1.0.113
482752,76bfc5ba-f552-42ea-ae62-9647d9158c6a,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Bayangan Dirimu,1,0,1.1.0.113,2014-06-07 15:06:50,NaN,NaT,1.1.0.113
482753,0e6a8c66-6990-47a3-a5f3-a070005682d8,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,i like music,5,0,1.1.0.113,2014-06-06 15:06:13,NaN,NaT,1.1.0.113
482754,fe187b46-97ee-4d7a-ad56-b45bc2a6ecdb,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Muzik My Life,5,0,1.1.0.113,2014-06-04 18:51:23,NaN,NaT,1.1.0.113
482755,61376942-e368-4358-b83e-ea442ca513dc,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Didik kempot,5,0,1.1.0.113,2014-05-30 07:47:46,NaN,NaT,1.1.0.113